# Generated by Django 5.1 on 2024-08-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='question',
            field=models.BooleanField(default=False),
        ),
    ]
