databases:
  - name: myboarddb
    plan: free
    databaseName: myboard
    user: myboard_user

services:
  - type: web
    plan: free
    name: myboard
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m uvicorn myboard.asgi:application --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myboarddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
